---
include:
  - board: eyelash_corne_left
    shield: nice_view
    artifact-name: eyelash_corne_left
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_right
    shield: nice_view
    artifact-name: eyelash_corne_right
    #snippet: zmk-usb-logging
  - board: eyelash_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=y
    artifact-name: eyelash_corne_studio_left
  - board: eyelash_corne_left
    shield: settings_reset
    artifact-name: eyelash_corne_settings_reset
    #snippet: zmk-usb-logging
